/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2020-04-30 22:26:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function($)\r\n");
      out.write("{\r\n");
      out.write("\t//ajax row data\r\n");
      out.write("\tvar ajax_data =\r\n");
      out.write("\t[\r\n");
      out.write("\t\t{fname:\"Code\", lname:\"With Mark\", email:\"mark@codewithmark.com\"}, \r\n");
      out.write("\t\t{fname:\"Mary\", lname:\"Moe\", email:\"mary@gmail.com\"},\r\n");
      out.write("\t\t{fname:\"John\", lname:\"Doe\", email:\"john@yahoo.com\"},\r\n");
      out.write("\t\t{fname:\"Julie\", lname:\"Dooley\", email:\"julie@gmail.com\"},\r\n");
      out.write("\t]\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tvar random_id = function  () \r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar id_num = Math.random().toString(9).substr(2,3);\r\n");
      out.write("\t\tvar id_str = Math.random().toString(36).substr(2);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn id_num + id_str;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t//--->create data table > start\r\n");
      out.write("\tvar tbl = '';\r\n");
      out.write("\ttbl +='<table class=\"table table-hover\">'\r\n");
      out.write("\r\n");
      out.write("\t\t//--->create table header > start\r\n");
      out.write("\t\ttbl +='<thead>';\r\n");
      out.write("\t\t\ttbl +='<tr>';\r\n");
      out.write("\t\t\ttbl +='<th>First Name</th>';\r\n");
      out.write("\t\t\ttbl +='<th>Last Name</th>';\r\n");
      out.write("\t\t\ttbl +='<th>Email</th>';\r\n");
      out.write("\t\t\ttbl +='<th>Options</th>';\r\n");
      out.write("\t\t\ttbl +='</tr>';\r\n");
      out.write("\t\ttbl +='</thead>';\r\n");
      out.write("\t\t//--->create table header > end\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//--->create table body > start\r\n");
      out.write("\t\ttbl +='<tbody>';\r\n");
      out.write("\r\n");
      out.write("\t\t\t//--->create table body rows > start\r\n");
      out.write("\t\t\t$.each(ajax_data, function(index, val) \r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t//you can replace with your database row id\r\n");
      out.write("\t\t\t\tvar row_id = random_id();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t//loop through ajax row data\r\n");
      out.write("\t\t\t\ttbl +='<tr row_id=\"'+row_id+'\">';\r\n");
      out.write("\t\t\t\t\ttbl +='<td ><div class=\"row_data\" edit_type=\"click\" col_name=\"fname\">'+val['fname']+'</div></td>';\r\n");
      out.write("\t\t\t\t\ttbl +='<td ><div class=\"row_data\" edit_type=\"click\" col_name=\"lname\">'+val['lname']+'</div></td>';\r\n");
      out.write("\t\t\t\t\ttbl +='<td ><div class=\"row_data\" edit_type=\"click\" col_name=\"email\">'+val['email']+'</div></td>';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t//--->edit options > start\r\n");
      out.write("\t\t\t\t\ttbl +='<td>';\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\ttbl +='<span class=\"btn_edit\" > <a href=\"#\" class=\"btn btn-link \" row_id=\"'+row_id+'\" > Edit</a> </span>';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t//only show this button if edit button is clicked\r\n");
      out.write("\t\t\t\t\t\ttbl +='<span class=\"btn_save\"> <a href=\"#\" class=\"btn btn-link\"  row_id=\"'+row_id+'\"> Save</a> | </span>';\r\n");
      out.write("\t\t\t\t\t\ttbl +='<span class=\"btn_cancel\"> <a href=\"#\" class=\"btn btn-link\" row_id=\"'+row_id+'\"> Cancel</a> | </span>';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\ttbl +='</td>';\r\n");
      out.write("\t\t\t\t\t//--->edit options > end\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\ttbl +='</tr>';\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t//--->create table body rows > end\r\n");
      out.write("\r\n");
      out.write("\t\ttbl +='</tbody>';\r\n");
      out.write("\t\t//--->create table body > end\r\n");
      out.write("\r\n");
      out.write("\ttbl +='</table>'\t\r\n");
      out.write("\t//--->create data table > end\r\n");
      out.write("\r\n");
      out.write("\t//out put table data\r\n");
      out.write("\t$(document).find('.tbl_user_data').html(tbl);\r\n");
      out.write("\r\n");
      out.write("\t$(document).find('.btn_save').hide();\r\n");
      out.write("\t$(document).find('.btn_cancel').hide(); \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t//--->make div editable > start\r\n");
      out.write("\t$(document).on('click', '.row_data', function(event) \r\n");
      out.write("\t{\r\n");
      out.write("\t\tevent.preventDefault(); \r\n");
      out.write("\r\n");
      out.write("\t\tif($(this).attr('edit_type') == 'button')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\treturn false; \r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t//make div editable\r\n");
      out.write("\t\t$(this).closest('div').attr('contenteditable', 'true');\r\n");
      out.write("\t\t//add bg css\r\n");
      out.write("\t\t$(this).addClass('bg-warning').css('padding','5px');\r\n");
      out.write("\r\n");
      out.write("\t\t$(this).focus();\r\n");
      out.write("\t})\t\r\n");
      out.write("\t//--->make div editable > end\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t//--->save single field data > start\r\n");
      out.write("\t$(document).on('focusout', '.row_data', function(event) \r\n");
      out.write("\t{\r\n");
      out.write("\t\tevent.preventDefault();\r\n");
      out.write("\r\n");
      out.write("\t\tif($(this).attr('edit_type') == 'button')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\treturn false; \r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar row_id = $(this).closest('tr').attr('row_id'); \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar row_div = $(this)\t\t\t\t\r\n");
      out.write("\t\t.removeClass('bg-warning') //add bg css\r\n");
      out.write("\t\t.css('padding','')\r\n");
      out.write("\r\n");
      out.write("\t\tvar col_name = row_div.attr('col_name'); \r\n");
      out.write("\t\tvar col_val = row_div.html(); \r\n");
      out.write("\r\n");
      out.write("\t\tvar arr = {};\r\n");
      out.write("\t\tarr[col_name] = col_val;\r\n");
      out.write("\r\n");
      out.write("\t\t//use the \"arr\"\tobject for your ajax call\r\n");
      out.write("\t\t$.extend(arr, {row_id:row_id});\r\n");
      out.write("\r\n");
      out.write("\t\t//out put to show\r\n");
      out.write("\t\t$('.post_msg').html( '<pre class=\"bg-success\">'+JSON.stringify(arr, null, 2) +'</pre>');\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\t\r\n");
      out.write("\t//--->save single field data > end\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\t//--->button > edit > start\t\r\n");
      out.write("\t$(document).on('click', '.btn_edit', function(event) \r\n");
      out.write("\t{\r\n");
      out.write("\t\tevent.preventDefault();\r\n");
      out.write("\t\tvar tbl_row = $(this).closest('tr');\r\n");
      out.write("\r\n");
      out.write("\t\tvar row_id = tbl_row.attr('row_id');\r\n");
      out.write("\r\n");
      out.write("\t\ttbl_row.find('.btn_save').show();\r\n");
      out.write("\t\ttbl_row.find('.btn_cancel').show();\r\n");
      out.write("\r\n");
      out.write("\t\t//hide edit button\r\n");
      out.write("\t\ttbl_row.find('.btn_edit').hide(); \r\n");
      out.write("\r\n");
      out.write("\t\t//make the whole row editable\r\n");
      out.write("\t\ttbl_row.find('.row_data')\r\n");
      out.write("\t\t.attr('contenteditable', 'true')\r\n");
      out.write("\t\t.attr('edit_type', 'button')\r\n");
      out.write("\t\t.addClass('bg-warning')\r\n");
      out.write("\t\t.css('padding','3px')\r\n");
      out.write("\r\n");
      out.write("\t\t//--->add the original entry > start\r\n");
      out.write("\t\ttbl_row.find('.row_data').each(function(index, val) \r\n");
      out.write("\t\t{  \r\n");
      out.write("\t\t\t//this will help in case user decided to click on cancel button\r\n");
      out.write("\t\t\t$(this).attr('original_entry', $(this).html());\r\n");
      out.write("\t\t}); \t\t\r\n");
      out.write("\t\t//--->add the original entry > end\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t//--->button > edit > end\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t//--->button > cancel > start\t\r\n");
      out.write("\t$(document).on('click', '.btn_cancel', function(event) \r\n");
      out.write("\t{\r\n");
      out.write("\t\tevent.preventDefault();\r\n");
      out.write("\r\n");
      out.write("\t\tvar tbl_row = $(this).closest('tr');\r\n");
      out.write("\r\n");
      out.write("\t\tvar row_id = tbl_row.attr('row_id');\r\n");
      out.write("\r\n");
      out.write("\t\t//hide save and cacel buttons\r\n");
      out.write("\t\ttbl_row.find('.btn_save').hide();\r\n");
      out.write("\t\ttbl_row.find('.btn_cancel').hide();\r\n");
      out.write("\r\n");
      out.write("\t\t//show edit button\r\n");
      out.write("\t\ttbl_row.find('.btn_edit').show();\r\n");
      out.write("\r\n");
      out.write("\t\t//make the whole row editable\r\n");
      out.write("\t\ttbl_row.find('.row_data')\r\n");
      out.write("\t\t.attr('edit_type', 'click')\r\n");
      out.write("\t\t.removeClass('bg-warning')\r\n");
      out.write("\t\t.css('padding','') \r\n");
      out.write("\r\n");
      out.write("\t\ttbl_row.find('.row_data').each(function(index, val) \r\n");
      out.write("\t\t{   \r\n");
      out.write("\t\t\t$(this).html( $(this).attr('original_entry') ); \r\n");
      out.write("\t\t});  \r\n");
      out.write("\t});\r\n");
      out.write("\t//--->button > cancel > end\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t//--->save whole row entery > start\t\r\n");
      out.write("\t$(document).on('click', '.btn_save', function(event) \r\n");
      out.write("\t{\r\n");
      out.write("\t\tevent.preventDefault();\r\n");
      out.write("\t\tvar tbl_row = $(this).closest('tr');\r\n");
      out.write("\r\n");
      out.write("\t\tvar row_id = tbl_row.attr('row_id');\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//hide save and cacel buttons\r\n");
      out.write("\t\ttbl_row.find('.btn_save').hide();\r\n");
      out.write("\t\ttbl_row.find('.btn_cancel').hide();\r\n");
      out.write("\r\n");
      out.write("\t\t//show edit button\r\n");
      out.write("\t\ttbl_row.find('.btn_edit').show();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t//make the whole row editable\r\n");
      out.write("\t\ttbl_row.find('.row_data')\r\n");
      out.write("\t\t.attr('edit_type', 'click')\r\n");
      out.write("\t\t.removeClass('bg-warning')\r\n");
      out.write("\t\t.css('padding','') \r\n");
      out.write("\r\n");
      out.write("\t\t//--->get row data > start\r\n");
      out.write("\t\tvar arr = {}; \r\n");
      out.write("\t\ttbl_row.find('.row_data').each(function(index, val) \r\n");
      out.write("\t\t{   \r\n");
      out.write("\t\t\tvar col_name = $(this).attr('col_name');  \r\n");
      out.write("\t\t\tvar col_val  =  $(this).html();\r\n");
      out.write("\t\t\tarr[col_name] = col_val;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//--->get row data > end\r\n");
      out.write("\r\n");
      out.write("\t\t//use the \"arr\"\tobject for your ajax call\r\n");
      out.write("\t\t$.extend(arr, {row_id:row_id});\r\n");
      out.write("\r\n");
      out.write("\t\t//out put to show\r\n");
      out.write("\t\t$('.post_msg').html( '<pre class=\"bg-success\">'+JSON.stringify(arr, null, 2) +'</pre>')\r\n");
      out.write("\t\t \r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t//--->save whole row entery > end\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}); \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<div class=\"panel panel-default\">\r\n");
      out.write("  <div class=\"panel-heading\"><b> Demo </b> </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"panel-body\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"tbl_user_data\"></div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<div class=\"panel panel-default\">\r\n");
      out.write("  <div class=\"panel-heading\"><b>HTML Table Edits/Upates</b> </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"panel-body\">\r\n");
      out.write("\t\r\n");
      out.write("\t<p>All the changes will be displayed below</p>\r\n");
      out.write("\t<div class=\"post_msg\"> </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
